#!/usr/bin/env python3
"""
Plot two OPV2V benchmark suites (e.g., pose-noise vs no-extr) in one consolidated figure.

Expected input:
- each run dir contains results_ap50_from_yaml.json generated by tools/summarize_opv2v_fullbench_from_yaml.py
- entries include at least ap30/ap50/ap70 and optionally infer_fps/pose_solver_avg_time_sec
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple


Key = Tuple[str, str, str, str, str]  # modality, sweep, method, strategy, noise


def normalize_noise(val: str) -> str:
    return f"{float(val):.1f}"


def load_entries(run_dir: Path) -> List[dict]:
    path = run_dir / "results_ap50_from_yaml.json"
    if not path.exists():
        raise FileNotFoundError(
            f"Missing {path}. Run tools/summarize_opv2v_fullbench_from_yaml.py first for this run dir."
        )
    obj = json.loads(path.read_text(encoding="utf-8"))
    entries = obj.get("entries")
    if not isinstance(entries, list):
        raise ValueError(f"Invalid entries in {path}")
    return entries


def build_series(entries: List[dict], *, modality: str, sweep: str, metric: str) -> Dict[Tuple[str, str], Dict[str, float]]:
    series: Dict[Tuple[str, str], Dict[str, float]] = defaultdict(dict)
    for e in entries:
        if e.get("modality") != modality or e.get("sweep") != sweep:
            continue
        method = str(e.get("method"))
        strategy = str(e.get("strategy"))
        noise = normalize_noise(str(e.get("noise")))
        v = e.get(metric)
        if isinstance(v, (int, float)):
            series[(method, strategy)][noise] = float(v)
    return dict(series)


def _plot_metric_grid(
    out_path: Path,
    *,
    title: str,
    suite_a_name: str,
    suite_b_name: str,
    suite_a_entries: List[dict],
    suite_b_entries: List[dict],
    modality: str,
    sweep: str,
    metrics: List[Tuple[str, str]],
    noise_axis: List[str],
) -> None:
    import matplotlib.pyplot as plt

    color_map = {
        "v2xregpp": "#1f77b4",
        "v2xregpp_occhint": "#0c5da5",
        "freealign": "#ff7f0e",
        "vips": "#2ca02c",
        "cbm": "#d62728",
        "baseline": "#7f7f7f",
        "oracle": "#9467bd",
        "single": "#000000",
    }
    style_map = {"best": "-", "stable": "--", "bounds": "-"}

    fig, axes = plt.subplots(
        nrows=len(metrics),
        ncols=2,
        figsize=(12.0, 3.8 * len(metrics)),
        sharex=True,
    )
    if len(metrics) == 1:
        axes = [axes]  # type: ignore[assignment]

    suites = [(suite_a_name, suite_a_entries), (suite_b_name, suite_b_entries)]
    x_vals = [float(x) for x in noise_axis]

    for row, (metric, ylabel) in enumerate(metrics):
        for col, (suite_name, entries) in enumerate(suites):
            ax = axes[row][col]
            series = build_series(entries, modality=modality, sweep=sweep, metric=metric)
            for (method, strategy), points in sorted(series.items()):
                ys = []
                for noise in noise_axis:
                    val = points.get(noise)
                    if val is None and method == "single":
                        val = points.get("0.0")
                    ys.append(val)
                if all(v is None for v in ys):
                    continue
                ax.plot(
                    x_vals,
                    ys,
                    color=color_map.get(method, "#333333"),
                    linestyle=style_map.get(strategy, "-"),
                    linewidth=1.8,
                    label=f"{method}-{strategy}",
                )
            ax.set_ylabel(ylabel)
            ax.grid(True, linestyle="--", alpha=0.35)
            if row == 0:
                ax.set_title(suite_name)
            if row == len(metrics) - 1:
                ax.set_xlabel("pos_std (m) / rot_std (deg)")

    # Put one global legend on the first subplot only.
    handles, labels = axes[0][0].get_legend_handles_labels()
    if handles:
        axes[0][0].legend(handles, labels, fontsize=7, ncol=2, loc="best")
    fig.suptitle(title, fontsize=12)
    fig.tight_layout(rect=[0, 0, 1, 0.98])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=200)


def main() -> None:
    ap = argparse.ArgumentParser(description="Plot dual-suite OPV2V curves in one figure.")
    ap.add_argument("--suite-a-run-dir", type=Path, required=True, help="Run dir for suite A (e.g., pose-noise).")
    ap.add_argument("--suite-b-run-dir", type=Path, required=True, help="Run dir for suite B (e.g., no-extr).")
    ap.add_argument("--suite-a-name", type=str, default="Pose-Noise (no pose_override)")
    ap.add_argument("--suite-b-name", type=str, default="No-Extr (pose_override=zero)")
    ap.add_argument("--modality", type=str, default="lidar", choices=["camera", "lidar"])
    ap.add_argument("--sweep", type=str, default="noise10", choices=["noise10", "drop20"])
    ap.add_argument(
        "--noise-axis",
        type=str,
        default="0,1,2,3,4,5,6,7,8,9,10",
        help="Comma-separated noise values.",
    )
    ap.add_argument("--out-dir", type=Path, default=None)
    args = ap.parse_args()

    suite_a_entries = load_entries(args.suite_a_run_dir)
    suite_b_entries = load_entries(args.suite_b_run_dir)
    noise_axis = [normalize_noise(v.strip()) for v in args.noise_axis.split(",") if v.strip()]

    out_dir = args.out_dir
    if out_dir is None:
        out_dir = args.suite_a_run_dir / "plots_yaml_dual_suite"
    out_dir.mkdir(parents=True, exist_ok=True)

    ap_out = out_dir / f"{args.modality}_{args.sweep}_dual_suite_ap.png"
    _plot_metric_grid(
        ap_out,
        title=f"OPV2V {args.modality} {args.sweep} AP Curves (Dual Suite)",
        suite_a_name=args.suite_a_name,
        suite_b_name=args.suite_b_name,
        suite_a_entries=suite_a_entries,
        suite_b_entries=suite_b_entries,
        modality=args.modality,
        sweep=args.sweep,
        metrics=[("ap30", "AP30"), ("ap50", "AP50"), ("ap70", "AP70")],
        noise_axis=noise_axis,
    )

    timing_out = out_dir / f"{args.modality}_{args.sweep}_dual_suite_timing.png"
    _plot_metric_grid(
        timing_out,
        title=f"OPV2V {args.modality} {args.sweep} Timing Curves (Dual Suite)",
        suite_a_name=args.suite_a_name,
        suite_b_name=args.suite_b_name,
        suite_a_entries=suite_a_entries,
        suite_b_entries=suite_b_entries,
        modality=args.modality,
        sweep=args.sweep,
        metrics=[("infer_fps", "infer_fps"), ("pose_solver_avg_time_sec", "pose_solver_avg_time_sec")],
        noise_axis=noise_axis,
    )

    print(f"Wrote AP figure: {ap_out}")
    print(f"Wrote timing figure: {timing_out}")


if __name__ == "__main__":
    main()
